**NYU DS Bootcamp Assignment2**

Part 1 - Numpy



In [1]:
import numpy as np
import pandas as pd

In [3]:
# Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [10]:
# 1. ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[4, 5, 6], [7, 8, 9]])

print(np.concatenate([A, B], axis = 0))
print(np.concatenate([A, B], axis = 1))


[[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [11]:
# 2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]
C = np.intersect1d(A, B)
print(C)

[4 5 6]


In [12]:
# 3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
D = A[np.where((A >= 5) & (A <= 10))]
print(D)

[5 6]


In [13]:
# 4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
Filterd = iris_2d[np.where((iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0))]
print(Filterd)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Part 2 - Pandas



In [19]:
# 1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

cols = ['Manufacturer', 'Model', 'Type']

Filtered1 = df.loc[:19, cols]  # 19 because loc needs to go one lower
print(Filtered1)


   Manufacturer       Model     Type
0         Acura     Integra    Small
1           NaN      Legend  Midsize
2          Audi          90  Compact
3          Audi         100  Midsize
4           BMW        535i  Midsize
5         Buick     Century  Midsize
6         Buick     LeSabre    Large
7         Buick  Roadmaster    Large
8         Buick     Riviera  Midsize
9      Cadillac     DeVille    Large
10     Cadillac     Seville  Midsize
11    Chevrolet    Cavalier  Compact
12    Chevrolet     Corsica  Compact
13    Chevrolet      Camaro   Sporty
14    Chevrolet      Lumina  Midsize
15    Chevrolet  Lumina_APV      Van
16    Chevrolet       Astro      Van
17    Chevrolet     Caprice    Large
18    Chevrolet    Corvette   Sporty
19          NaN    Concorde    Large


In [20]:
# 2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())
print(df)



   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [22]:
# 3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

df_new = df[df.sum(axis = 1) > 100]
print(df_new)

     0   1   2   3
1   12  39  26  26
2   24  31  39  36
3   29  36  18  29
4   25  25  20  36
5   37  35  18  39
7   16  33  29  35
8   38  21  19  33
10  11  26  32  34
11  25  26  21  35
13  36  23  19  29
